[package]
name = "lac"
version = "0.1.0"
edition = "2021"

[features]
default = []
use_bindgen = ["bindgen"]
use_sdk_stubs = []

[dependencies]

[build-dependencies]
cc = "1.0"
bindgen = { version = "0.71.1", optional = true }

[dev-dependencies]
lac = { path = ".", features = ["use_sdk_stubs"] }
