[package]
name = "lac"
version = "0.1.0"
edition = "2021"

[features]
default = []
bindgen = ["bindgen"]
sdk_stub = []

[dependencies]

[build-dependencies]
cc = "1.0"
bindgen = { version = "0.71.1", optional = true }

[dev-dependencies]
lac = { path = ".", features = ["sdk_stub"] }
